def help_menu(pos):

    if pos == 'default':
        print("\n")
        print("\t    ╔═════════════════════════════════════════════════════════════════════════════════════════════╗")
        print("\t    ║      Welcome to Radar! This command line interface is here to assist your needs.            ║")
        print("\t    ║                                                                                             ║")
        print("\t    ║      This program currently has 10 options for you to choose from. The options are:         ║")
        print("\t    ║                                                                                             ║")
        print("\t    ║      1. Weather - This option displays weather of the zip code you initially typed          ║")
        print("\t    ║                   in when you started the program. You may view different city's            ║")
        print("\t    ║                   weather by choosing option #6 and then input another zip code.            ║")
        print("\t    ║                                                                                             ║")
        print("\t    ║      2. News for <city name> - This option displays the news that mentions anything         ║")
        print("\t    ║                                about that city. This option takes the zip code from         ║")
        print("\t    ║                                the program and then automatically searches news             ║")
        print("\t    ║                                regarding that city. If you would like to view the           ║")
        print("\t    ║                                news about another city, choose option #6 from the           ║")
        print("\t    ║                                main menu.                                                   ║")
        print("\t    ║                                                                                             ║")
        print("\t    ║      3. Search the News - This option searches the news using any input you type in.        ║")
        print("\t    ║                           Ex. 'tesla' <- without using single quotations.                   ║")
        print("\t    ║                                                                                             ║")
        print("\t    ║      4. Time Zone - This option displays the time zone of the zip code that you             ║")
        print("\t    ║                     entered at the beginning of the program. If you wish to view            ║")
        print("\t    ║                     the time zone of another city, choose option #6 in the main             ║")
        print("\t    ║                     menu and enter your preferred zip code.                                 ║")
        print("\t    ║                                                                                             ║")
        print("\t    ║      5. Tax Rate - This option displays the tax rate of the city that was inputted          ║")
        print("\t    ║                    via the zip code. If you wish to view another city, choose               ║")
        print("\t    ║                    option #6 at the main menu to input another zip code.                    ║")
        print("\t    ║                                                                                             ║")
        print("\t    ║      6. Enter New Zip Code - This option allows you to enter another zip code.              ║")
        print("\t    ║                              Must be 5 digits long.                                         ║")
        print("\t    ║                                                                                             ║")
        print("\t    ║      7. Generate Password - This option generates password in length of 8-32                ║")
        print("\t    ║                             characters long. By default, passwords are in all               ║")
        print("\t    ║                             lowercase. There will be options that asks you if you           ║")
        print("\t    ║                             want to include special characters, uppercase letters,          ║")
        print("\t    ║                             and/or digits. You will be prompted by inputting 'Y' for        ║")
        print("\t    ║                             yes or 'N' for no.                                              ║")
        print("\t    ║                                                                                             ║")
        print("\t    ║      8. Blackjack! - This option starts a classic game of blackjack. You will start         ║")
        print("\t    ║                      first by either 'hitting' or 'staying'. If your score goes above       ║")
        print("\t    ║                      21, you automatically lose. If you chose to stay, the dealer           ║")
        print("\t    ║                      will try to match your score or score higher to beat you.              ║")
        print("\t    ║                                                                                             ║")
        print("\t    ║      9. FBI Top Secret Documents - This option allows you to view the top secret            ║")
        print("\t    ║                                    documents from the FBI servers. FYI, it's                ║")
        print("\t    ║                                    a prank for those gullible fellows.                      ║")
        print("\t    ║                                                                                             ║")
        print("\t    ║      10. Exit - This option exits the program. You will see a farewell message before       ║")
        print("\t    ║                 the programs exit successfully.                                             ║")
        print("\t    ╚═════════════════════════════════════════════════════════════════════════════════════════════╝\n")
        input("\n\033[32mPress Enter to go back... \033[0m")

    if pos == 'weather':
        print("\n")
        print("\t    ╔═════════════════════════════════════════════════════════════════════════════════════════════╗")
        print("\t    ║                                          Weather                                            ║")
        print("\t    ║                                                                                             ║")
        print("\t    ║       This program displays weather of the zip code you initially typed in when you         ║")
        print("\t    ║        started the program. You may view different city's weather by choosing option        ║")
        print("\t    ║                            #6 and then input another zip code.                              ║")
        print("\t    ╚═════════════════════════════════════════════════════════════════════════════════════════════╝\n")
        input("\n\033[32mPress Enter to go back... \033[0m")

    if pos == 'news':
        print("\n")
        print("\t    ╔═════════════════════════════════════════════════════════════════════════════════════════════╗")
        print("\t    ║                                           News                                              ║")
        print("\t    ║                                                                                             ║")
        print("\t    ║                This program searches the news using any input you type in.                  ║")
        print("\t    ║                      Ex. 'tesla' <- without using single quotations.                        ║")
        print("\t    ╚═════════════════════════════════════════════════════════════════════════════════════════════╝\n")
        input("\n\033[32mPress Enter to go back... \033[0m")

    if pos == 'time':
        print("\n")
        print("\t    ╔═════════════════════════════════════════════════════════════════════════════════════════════╗")
        print("\t    ║                                         Time Zone                                           ║")
        print("\t    ║                                                                                             ║")
        print("\t    ║                This program displays the time zone of the zip code that you                 ║")
        print("\t    ║                entered at the beginning of the program. If you wish to view                 ║")
        print("\t    ║                the time zone of another city, choose option #6 in the main                  ║")
        print("\t    ║                           menu and enter your preferred zip code.                           ║")
        print("\t    ║                                                                                             ║")
        print("\t    ║                     Current time is in military time and standard time.                     ║")
        print("\t    ╚═════════════════════════════════════════════════════════════════════════════════════════════╝\n")
        input("\n\033[32mPress Enter to go back... \033[0m")

    if pos == 'password':
        print("\n")
        print("\t    ╔═════════════════════════════════════════════════════════════════════════════════════════════╗")
        print("\t    ║                                     Password Generator                                      ║")
        print("\t    ║                                                                                             ║")
        print("\t    ║        This program generates password in length of 8-32 characters long. By default,       ║")
        print("\t    ║          passwords are in all lowercase. There will be options that asks you if you         ║")
        print("\t    ║        want to include special characters, uppercase letters, and/or digits. You will       ║")
        print("\t    ║                    be prompted by inputting 'Y' for yes or 'N' for no.                      ║")
        print("\t    ║                                                                                             ║")
        print("\t    ║         Once the password is generated, you will also be given a prompt to save the         ║")
        print("\t    ║         password to the Downloads folder. You can either hit 'Y' for yes or 'N' for         ║")
        print("\t    ║          no. If chosen no, the password will not get saved and will be discarded. You       ║")
        print("\t    ║           will then get a farewell message saying thank you for using the password          ║")
        print("\t    ║                                         generator.                                          ║")
        print("\t    ╚═════════════════════════════════════════════════════════════════════════════════════════════╝\n")
        input("\n\033[32mPress Enter to go back... \033[0m")

    if pos == 'blackjack':
        print("\n")
        print("\t    ╔═════════════════════════════════════════════════════════════════════════════════════════════╗")
        print("\t    ║                                         Blackjack!                                          ║")
        print("\t    ║                                                                                             ║")
        print("\t    ║       This program starts a classic game of blackjack. You will start first by either       ║")
        print("\t    ║       'hitting' or 'staying'. If your score goes above 21, you automatically lose. If       ║")
        print("\t    ║        you chose to stay, the dealer will try to match your score or score higher to        ║")
        print("\t    ║                                          beat you.                                          ║")
        print("\t    ║                                                                                             ║")
        print("\t    ║                                  \033[31m         RULES\033[0m                                             ║")
        print("\t    ║         The main goal for this game is to score 21 without going over. You can choose       ║")
        print("\t    ║              to stay if your score is close to 21 or at any point of the game. If           ║")
        print("\t    ║                           you go over 21, you automatically lose.                           ║")
        print("\t    ║                                                                                             ║")
        print("\t    ║         Each player (Dealer and You) will start with 2 cards. If either one of you get      ║")
        print("\t    ║          a blackjack, that player automatically wins. If both of you get blackjack on       ║")
        print("\t    ║         the first two cards, it's a draw. Either way, you will then be prompted to          ║")
        print("\t    ║          start a new game. If you do not want to start a new game, this Blackjack!          ║")
        print("\t    ║                    program will exit and take you back to the main menu.                    ║")
        print("\t    ║                                                                                             ║")
        print("\t    ║          Each player will have a maximum of 4 cards. If you have reached the limit          ║")
        print("\t    ║         of 4 cards and your score is below 21, the dealer will then 'hit' until they        ║")
        print("\t    ║         tie or score higher than you. If the dealer goes above 21, the dealer loses.        ║")
        print("\t    ║                                                                                             ║")
        print("\t    ║          Aces will start with the value of 11. If the score goes over 21, and either        ║")
        print("\t    ║            players have Aces, the value of Aces will then change to the value of 1.         ║")
        print("\t    ║                                                                                             ║")
        print("\t    ║                      Jacks (J), Queens (Q), and Kings (K) are worth 10.                     ║")
        print("\t    ║                                                                                             ║")
        print("\t    ║                                         HAVE FUN!                                           ║")
        print("\t    ╚═════════════════════════════════════════════════════════════════════════════════════════════╝\n")
        input("\n\033[32mPress Enter to go back... \033[0m")

    if pos == 'rickroll':
        print("\n")
        print("\t    ╔═════════════════════════════════════════════════════════════════════════════════════════════╗")
        print("\t    ║                                 FBI Top Secret Documents                                    ║")
        print("\t    ║                                                                                             ║")
        print("\t    ║       This program displays top-secret files from the FBI servers. Enter if you dare!       ║")
        print("\t    ╚═════════════════════════════════════════════════════════════════════════════════════════════╝\n")
        input("\n\033[32mPress Enter to go back... \033[0m")
